/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import org.apache.kafka.clients.admin.NewTopic;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.kafka.annotation.EnableKafkaStreams;
import org.springframework.kafka.config.TopicBuilder;
import org.apache.kafka.streams.state.KeyValueBytesStoreSupplier;
import org.apache.kafka.streams.state.Stores;

@SpringBootApplication
@EnableKafkaStreams
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }

    @Bean
    NewTopic hobbit() {
        return TopicBuilder.name("hobbit").partitions(3).replicas(1).build();
    }

    @Bean
    NewTopic counts() {
        return TopicBuilder.name("streams-wordcount-output").partitions(3).replicas(1).build();
    }

    @Bean
    KeyValueBytesStoreSupplier storeSupplier() {
        return Stores.inMemoryKeyValueStore("in-memory-counts");
    }
}